service: chatgpt-audio-chatbot

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1

plugins:
  - serverless-python-requirements

functions:
  chatgpt-audio-chatbot:
    handler: handler.handler
    timeout: 30
    events:
      - http:
          path: get-answer
          method: post
          cors: true